#!/usr/bin/env python3
"""Regenerate docs/AGENTS.md's "Global" table from claude-agents/*.md frontmatter.

Why this exists: before 2026-09-16, docs/AGENTS.md's Global table was hand-written and hand-edited
one PR at a time (see PR #50, #52) as the live roster under ~/.claude/agents grew past what the
doc tracked -- it reached 70 live agents while the doc indexed 25. A hand-written index rots
independently of the files it describes, silently, the same way any hand-maintained copy drifts
from its source. This script removes the hand-editing step: the table is derived from the actual
committed files every time, so the two cannot silently diverge.

Usage:
    python tools/generate_agents_md.py            # print the table to stdout
    python tools/generate_agents_md.py --write     # replace the Global table in docs/AGENTS.md

Only the "## Global (...)" section of docs/AGENTS.md is touched -- the "MasterThread/.claude/agents/"
and "Repo-local" sections describe agents that don't live in claude-agents/, so they're left alone.

KNOWN GAP as of 2026-09-16: PR #52 (open at the time this script was written) adds a Role column
(A = advisor / R = researcher, per the new `standards/sessions/advisor_role.md`) to every table,
plus a whole "Advisors against MasterThread's own standards" section this script does not generate.
This script currently emits Agent/Model/Access/Purpose only -- it was deliberately NOT run against
docs/AGENTS.md in the PR that introduced it, specifically to avoid clobbering #52's classification
work with a naive regeneration. Before running --write again: extend `build_rows`/`render_table`
to read and preserve the Role column (the classification itself is an editorial judgment call made
per-agent in #52, not something to re-derive from frontmatter -- read the merged table, don't
guess), then regenerate. Until then, treat this as a tool for the *next* person to finish, not a
drop-in replacement for #52.
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
AGENTS_DIR = ROOT / "claude-agents"
AGENTS_MD = ROOT / "docs" / "AGENTS.md"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)
WRITE_TOOLS = {"Write", "Edit", "NotebookEdit"}


def parse_frontmatter(text: str) -> dict:
    m = FRONTMATTER_RE.match(text)
    if not m:
        raise ValueError("no frontmatter block found")
    fields: dict[str, str] = {}
    key = None
    for line in m.group(1).splitlines():
        if not line.strip():
            continue
        kv = re.match(r"^([A-Za-z_]+):\s*(.*)$", line)
        if kv:
            key, val = kv.group(1), kv.group(2).strip()
            fields[key] = val
        elif key:
            # continuation line (frontmatter value wrapped across lines)
            fields[key] += " " + line.strip()
    return fields


def one_liner(description: str) -> str:
    """First clause of the description field, trimmed to keep the table scannable."""
    # descriptions are written as "Use when X. Does Y." or "Use to X ... -- Z"; take up to the
    # first " -- " or first ". " after a reasonable length, else the whole thing capped at a word
    # boundary (never mid-word) with an ellipsis.
    for sep in (" -- ", ". "):
        idx = description.find(sep)
        if idx != -1 and idx < 160:
            return description[:idx].strip().rstrip(".")
    limit = 140
    if len(description) <= limit:
        return description.strip().rstrip(".")
    cut = description[:limit].rsplit(" ", 1)[0]
    return cut.strip().rstrip(".,;") + "…"


def classify(tools: str) -> str:
    tool_list = {t.strip() for t in tools.split(",")}
    return "write" if tool_list & WRITE_TOOLS else "read-only"


def build_rows() -> list[tuple[str, str, str, str, str]]:
    rows = []
    for path in sorted(AGENTS_DIR.glob("*.md")):
        if path.name == "SYNC.md":
            continue
        fields = parse_frontmatter(path.read_text(encoding="utf-8"))
        name = fields.get("name", path.stem)
        model = fields.get("model", "?")
        tools = fields.get("tools", "")
        description = fields.get("description", "")
        rows.append((name, model, classify(tools), one_liner(description), tools))
    return rows


def render_table(rows: list[tuple[str, str, str, str, str]]) -> str:
    write_count = sum(1 for r in rows if r[2] == "write")
    lines = [
        f"_Generated by `tools/generate_agents_md.py` from `claude-agents/*.md` frontmatter — "
        f"do not hand-edit this table. {len(rows)} agents, {write_count} write-capable "
        f"(has Write/Edit/NotebookEdit), {len(rows) - write_count} read-only by tool grant._",
        "",
        "| Agent | Model | Access | Purpose |",
        "|---|---|---|---|",
    ]
    for name, model, access, purpose, _tools in rows:
        lines.append(f"| `{name}` | {model} | {access} | {purpose} |")
    return "\n".join(lines) + "\n"


def replace_global_section(doc: str, table: str) -> str:
    # Global section runs from its "## Global (...)" heading to the next "## " heading.
    pattern = re.compile(
        r"(## Global \(`~/\.claude/agents/`, available in every repo\)\n\n)"
        r".*?"
        r"(\n\n## )",
        re.DOTALL,
    )
    replacement = r"\1" + table.replace("\\", "\\\\") + r"\2"
    new_doc, count = pattern.subn(replacement, doc)
    if count != 1:
        raise SystemExit(
            "could not find exactly one Global section to replace in docs/AGENTS.md "
            f"(found {count}) -- check the heading text hasn't changed"
        )
    return new_doc


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write docs/AGENTS.md in place")
    args = parser.parse_args()

    rows = build_rows()
    table = render_table(rows)

    if not args.write:
        sys.stdout.write(table)
        return 0

    doc = AGENTS_MD.read_text(encoding="utf-8")
    new_doc = replace_global_section(doc, table)
    AGENTS_MD.write_text(new_doc, encoding="utf-8")
    print(f"Wrote {len(rows)} agents into {AGENTS_MD}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
